package com.example.myfood

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class Food(
    val foodId: Int,
    val foodTitle: String,
    val foodDescription: String,
    val foodTime: Int,
    val foodServings: Int,
    val foodYoutubeLink: String,
    val foodIngredientImages: List<Int>,
    val foodMeal: String,
    val foodCourse: String,
    val foodImage: Int
): Parcelable

val myFoodList = listOf(
    Food(
        foodId = 1,
        foodTitle = "Scrambled Eggs",
        foodDescription = "For a perfect scrambled eggs breakfast, crack the eggs into a bowl and whisk them with a splash of milk. Melt butter in a non-stick skillet over medium-low heat. Pour the eggs into the skillet and let them sit for a moment until they start to set. Gently stir the eggs with a spatula, allowing them to cook evenly and form soft curds. Remove from heat just before they're fully set to prevent overcooking. Serve immediately for a delicious, fluffy breakfast!",
        foodTime = 15,
        foodServings = 2,
        foodYoutubeLink = "https://www.youtube.com/watch?v=7goNbTdFwNM",
        foodIngredientImages = listOf(R.drawable.egg, R.drawable.butter, R.drawable.milk),
        foodCourse = "Breakfast",
        foodMeal = "Main Dish",
        foodImage = R.drawable.scrambledegg
    ),
    Food(
        foodId = 2,
        foodTitle = "Tomato Pasta",
        foodDescription = "Start by boiling pasta in salted water until al dente. In a separate pan, sauté minced garlic and chopped onions in olive oil until translucent. Add diced tomatoes and let them simmer until they break down into a sauce. Season with salt and pepper to taste. Toss the cooked pasta into the tomato sauce, ensuring the pasta is coated evenly. Garnish with fresh basil and grated cheese before serving.",
        foodTime = 20,
        foodServings = 4,
        foodYoutubeLink = "https://www.youtube.com/watch?v=Svk1SwdL1eg",
        foodIngredientImages = listOf(R.drawable.pasta, R.drawable.tomato, R.drawable.garlic, R.drawable.oil),
        foodCourse = "Lunch",
        foodMeal = "Main Dish",
        foodImage = R.drawable.tomatopasta
    ),
    Food(
        foodId = 3,
        foodTitle = "Banana Bread",
        foodDescription = "Preheat the oven and grease a loaf pan. Mash ripe bananas in a bowl and mix in melted butter, honey, and flour until well combined. Pour the batter into the loaf pan and bake until a toothpick inserted into the center comes out clean. Allow the banana bread to cool before slicing. Enjoy this moist and flavorful treat for breakfast or as a snack!",
        foodTime = 10,
        foodServings = 1,
        foodYoutubeLink = "https://www.youtube.com/watch?v=vPUuY-bEK2w",
        foodIngredientImages = listOf(R.drawable.banana, R.drawable.flour, R.drawable.butter, R.drawable.honey),
        foodCourse = "Breakfast",
        foodMeal = "Dessert",
        foodImage = R.drawable.bananabread
    ),
    Food(
        foodId = 4,
        foodTitle = "Cheese Omelette",
        foodDescription = "Whisk eggs in a bowl and season with salt and pepper. Melt butter in a non-stick skillet over medium heat. Pour in the eggs and let them cook until the edges start to set. Sprinkle grated cheese over one half of the omelette and let it melt slightly. Fold the other half over the cheese and cook for a minute until the cheese is fully melted. Slide the omelette onto a plate and serve with toast or a side salad.",
        foodTime = 15,
        foodServings = 2,
        foodYoutubeLink = "https://www.youtube.com/watch?v=-ZnK6OgRqqY",
        foodIngredientImages = listOf(R.drawable.egg, R.drawable.cheese, R.drawable.butter),
        foodCourse = "Breakfast",
        foodMeal = "Main Dish",
        foodImage = R.drawable.cheeseomelette
    ),
    Food(
        foodId = 5,
        foodTitle = "Tomato Soup",
        foodDescription = "In a pot, melt butter and sauté minced garlic and diced onions until soft. Add chopped tomatoes and water, bringing the mixture to a simmer. Let it cook until the tomatoes break down and the flavors meld together. Use an immersion blender to blend the soup until smooth. Season with salt and pepper, and garnish with fresh herbs before serving this comforting soup.",
        foodTime = 30,
        foodServings = 4,
        foodYoutubeLink = "https://www.youtube.com/watch?v=szjZ3vqwyXE",
        foodIngredientImages = listOf(R.drawable.tomato, R.drawable.garlic, R.drawable.onion, R.drawable.butter, R.drawable.water),
        foodCourse = "Dinner",
        foodMeal = "Soup",
        foodImage = R.drawable.tomatosoup
    ),
    Food(
        foodId = 6,
        foodTitle = "Potato Pancakes",
        foodDescription = "Grate potatoes and mix them with flour, beaten eggs, and a pinch of salt. Heat butter in a skillet over medium heat. Spoon the potato mixture into the skillet, flattening them with a spatula. Cook until golden brown on both sides. Serve these crispy pancakes as a side dish or a tasty snack with sour cream or applesauce.",
        foodTime = 15,
        foodServings = 2,
        foodYoutubeLink = "https://youtu.be/5ocdVtv5-bA?si=MeT0PuGbFR3vluXV",
        foodIngredientImages = listOf(R.drawable.egg, R.drawable.butter, R.drawable.potato, R.drawable.flour),
        foodCourse = "Breakfast",
        foodMeal = "Main Dish",
        foodImage = R.drawable.potatopancake
    ),
    Food(
        foodId = 7,
        foodTitle = "Berry Smoothie",
        foodDescription = "Blend mixed berries, a ripe banana, milk, and a drizzle of honey until smooth and creamy. Adjust the sweetness to your liking by adding more honey if desired. Pour into glasses and enjoy this refreshing and nutritious smoothie for a quick breakfast or a satisfying snack.",
        foodTime = 10,
        foodServings = 1,
        foodYoutubeLink = "https://youtu.be/J83nEr7sg3c?si=htLT-7dYZQoYWJqK",
        foodIngredientImages = listOf(R.drawable.berry, R.drawable.banana, R.drawable.milk, R.drawable.honey),
        foodCourse = "Breakfast",
        foodMeal = "Appetizer",
        foodImage = R.drawable.berrysmoothie
    ),
    Food(
        foodId = 8,
        foodTitle = "Chicken Sandwich",
        foodDescription = "Marinate chicken breasts in your preferred seasoning and cook them until fully done. Toast slices of bread and spread mayonnaise on one side. Layer the bread with lettuce, sliced tomatoes, cooked chicken, and cheese. Top with another slice of bread and serve this hearty sandwich with a side of chips or a fresh salad.",
        foodTime = 50,
        foodServings = 1,
        foodYoutubeLink = "https://www.youtube.com/watch?v=NqJtUVhAdNw",
        foodIngredientImages = listOf(R.drawable.chicken, R.drawable.bread, R.drawable.lettuce, R.drawable.tomato, R.drawable.cheese),
        foodCourse = "Lunch",
        foodMeal = "Main Dish",
        foodImage = R.drawable.chickensandwich
    ),
    Food(
        foodId = 9,
        foodTitle = "Garlic Butter Shrimp",
        foodDescription = "Peel and devein shrimp, then pat them dry. In a skillet, melt butter and sauté minced garlic until fragrant. Add the shrimp and cook until they turn pink and opaque. Sprinkle chopped parsley over the shrimp and toss to coat. Serve this flavorful garlic butter shrimp over rice or pasta for a delightful meal.",
        foodTime = 40,
        foodServings = 4,
        foodYoutubeLink = "https://www.youtube.com/watch?v=f8wO2wsaUz0",
        foodIngredientImages = listOf(R.drawable.shrimp, R.drawable.butter, R.drawable.garlic, R.drawable.parsley),
        foodCourse = "Dinner",
        foodMeal = "Main Dish",
        foodImage = R.drawable.garlicbuttershrimp
    ),
    Food(
        foodId = 10,
        foodTitle = "Cheeseburger",
        foodDescription = "Form ground beef into patties and season them generously with salt and pepper. Cook the patties on a grill or in a skillet until they reach your preferred doneness. Toast burger buns and assemble the cheeseburgers with lettuce, tomato slices, onion, and cheese. Add condiments of your choice and enjoy this classic comfort food!",
        foodTime = 55,
        foodServings = 6,
        foodYoutubeLink = "https://www.youtube.com/watch?v=-B6FvKbq2Uw",
        foodIngredientImages = listOf(R.drawable.groundbeef, R.drawable.cheese, R.drawable.tomato, R.drawable.lettuce, R.drawable.onion, R.drawable.bread),
        foodCourse = "Breakfast",
        foodMeal = "Main Dish",
        foodImage = R.drawable.cheeseburger
    ),
    Food(
        foodId = 11,
        foodTitle = "Vegetable Stir-Fry",
        foodDescription = "Heat oil in a wok or skillet and add chopped onions, peppers, garlic, corn, and peas. Stir-fry the vegetables until they're tender yet crisp. Season with soy sauce or your favorite stir-fry sauce. Serve this colorful medley of veggies over steamed rice for a quick and nutritious meal.",
        foodTime = 30,
        foodServings = 2,
        foodYoutubeLink = "https://www.youtube.com/watch?v=h8IXBipqYgs",
        foodIngredientImages = listOf(R.drawable.onion, R.drawable.pepper, R.drawable.garlic, R.drawable.tomato, R.drawable.corn, R.drawable.peas),
        foodCourse = "Dinner",
        foodMeal = "Side",
        foodImage = R.drawable.vegetablestirfry
    ),
    Food(
        foodId = 12,
        foodTitle = "Honey Glazed Carrots",
        foodDescription = "Steam or boil carrots until they're tender. In a skillet, melt butter and add honey. Toss the cooked carrots in the honey-butter mixture until they're coated evenly. Sprinkle a pinch of salt and serve these glazed carrots as a delightful side dish.",
        foodTime = 15,
        foodServings = 2,
        foodYoutubeLink = "https://www.youtube.com/watch?v=qYfoARhooHE",
        foodIngredientImages = listOf(R.drawable.carrot, R.drawable.honey, R.drawable.butter),
        foodCourse = "Dinner",
        foodMeal = "Appetizer",
        foodImage = R.drawable.honeyglazedcarrots
    ),
    Food(
        foodId = 13,
        foodTitle = "Lentil Soup",
        foodDescription = "Rinse lentils and boil them in water until they soften. In another pot, sauté chopped onions and garlic until golden brown. Add the cooked lentils to the pot along with diced tomatoes and simmer until flavors meld. Season with salt, pepper, and chopped parsley. Enjoy this hearty lentil soup with a slice of bread.",
        foodTime = 55,
        foodServings = 4,
        foodYoutubeLink = "https://www.youtube.com/watch?v=hfL7CPhku2I",
        foodIngredientImages = listOf(R.drawable.lentil, R.drawable.onion, R.drawable.garlic, R.drawable.tomato, R.drawable.parsley),
        foodCourse = "Lunch",
        foodMeal = "Soup",
        foodImage = R.drawable.lentilsoup
    ),
    Food(
        foodId = 14,
        foodTitle = "Spinach Salad",
        foodDescription = "Toss fresh spinach leaves with sliced tomatoes and crumbled cheese of your choice. Drizzle with your preferred vinaigrette or a simple olive oil and vinegar dressing. Add some freshly ground black pepper for a burst of flavor and serve this refreshing salad as a side or a light meal.",
        foodTime = 15,
        foodServings = 1,
        foodYoutubeLink = "https://www.youtube.com/watch?v=zHToir532B4",
        foodIngredientImages = listOf(R.drawable.spinach, R.drawable.tomato, R.drawable.cheese),
        foodCourse = "Lunch",
        foodMeal = "Side",
        foodImage = R.drawable.spinachsalad
    ),
    Food(
        foodId = 15,
        foodTitle = "Chicken Curry",
        foodDescription = "Sauté diced onions and minced garlic in oil until golden. Add cubed chicken and cook until browned. Stir in diced tomatoes and spices like curry powder, cumin, and paprika. Simmer until the chicken is cooked through and the sauce thickens. Serve this aromatic chicken curry over steamed rice or with naan bread.",
        foodTime = 30,
        foodServings = 2,
        foodYoutubeLink = "https://www.youtube.com/watch?v=WRYOVVexMhU",
        foodIngredientImages = listOf(R.drawable.chicken, R.drawable.tomato, R.drawable.onion, R.drawable.garlic),
        foodCourse = "Dinner",
        foodMeal = "Main Dish",
        foodImage = R.drawable.chickencurry
    ),
    Food(
        foodId = 16,
        foodTitle = "Garlic Bread",
        foodDescription = "Preheat the oven. Slice a baguette lengthwise and spread a mixture of butter, minced garlic, and chopped parsley on each half. Sprinkle grated cheese over the top. Bake until the bread is crispy and the cheese is melted. Serve this fragrant garlic bread as a side to complement pasta dishes or soups.",
        foodTime = 20,
        foodServings = 2,
        foodYoutubeLink = "https://www.youtube.com/watch?v=wBFrmiDDIek",
        foodIngredientImages = listOf(R.drawable.bread, R.drawable.butter, R.drawable.garlic),
        foodCourse = "Breakfast",
        foodMeal = "Appetizer",
        foodImage = R.drawable.garlicbread
    ),
    Food(
        foodId = 17,
        foodTitle = "Cheesy Potato Casserole",
        foodDescription = "Thinly slice potatoes and layer them in a baking dish. Mix melted butter and grated cheese, then pour it over the potatoes. Bake until the potatoes are tender and the cheese is golden and bubbly. Garnish with chopped parsley before serving this comforting casserole.",
        foodTime = 30,
        foodServings = 2,
        foodYoutubeLink = "https://www.youtube.com/watch?v=eqgLQhXokJY",
        foodIngredientImages = listOf(R.drawable.potato, R.drawable.butter, R.drawable.cheese),
        foodCourse = "Lunch",
        foodMeal = "Main Dish",
        foodImage = R.drawable.cheesypotatocasserole
    ),
    Food(
        foodId = 18,
        foodTitle = "Pepper Steak",
        foodDescription = "Slice beef into strips and marinate in soy sauce. Sauté sliced onions and peppers in oil until softened. Add the marinated beef and cook until it's browned. Season with black pepper and a splash of soy sauce. Serve this savory pepper steak with rice or noodles.",
        foodTime = 45,
        foodServings = 4,
        foodYoutubeLink = "https://www.youtube.com/watch?v=IM6wXmo0gQw",
        foodIngredientImages = listOf(R.drawable.groundbeef, R.drawable.pepper, R.drawable.onion),
        foodCourse = "Dinner",
        foodMeal = "Main Dish",
        foodImage = R.drawable.peppersteak
    ),
    Food(
        foodId = 19,
        foodTitle = "Tomato Basil Bruschetta",
        foodDescription = "Dice tomatoes and mix them with minced garlic, chopped basil, olive oil, salt, and pepper. Toast slices of bread until golden and crisp. Top the bread with the tomato mixture and a drizzle of balsamic glaze. Serve this fresh and vibrant bruschetta as an appetizer.",
        foodTime = 15,
        foodServings = 2,
        foodYoutubeLink = "https://www.youtube.com/watch?v=Q3xg35pcLyo",
        foodIngredientImages = listOf(R.drawable.tomato, R.drawable.garlic, R.drawable.bread, R.drawable.basil),
        foodCourse = "Lunch",
        foodMeal = "Side",
        foodImage = R.drawable.tomatobasilbruschetta
    ),
    Food(
        foodId = 20,
        foodTitle = "Banana Pancakes",
        foodDescription = "Mash ripe bananas in a bowl and mix in flour, beaten egg, and a splash of milk to create a pancake batter. Heat a skillet and pour the batter to make pancakes. Cook until bubbles form, then flip and cook until golden brown. Serve these fluffy banana pancakes with a drizzle of honey or maple syrup.",
        foodTime = 25,
        foodServings = 3,
        foodYoutubeLink = "https://www.youtube.com/watch?v=NbGPOTDf6Jc",
        foodIngredientImages = listOf(R.drawable.banana, R.drawable.flour, R.drawable.milk, R.drawable.egg),
        foodCourse = "Breakfast",
        foodMeal = "Side",
        foodImage = R.drawable.bananapancakes
    ),
    Food(
        foodId = 21,
        foodTitle = "Chicken Caesar Salad",
        foodDescription = "Grill or cook chicken until fully cooked, then slice it. Toss chopped romaine lettuce with Caesar dressing until well coated. Add the sliced chicken, croutons, and grated cheese. Toss everything together and serve this classic salad as a delicious and satisfying meal.",
        foodTime = 25,
        foodServings = 2,
        foodYoutubeLink = "https://www.youtube.com/watch?v=AGwfmY60FOM",
        foodIngredientImages = listOf(R.drawable.chicken, R.drawable.lettuce, R.drawable.cheese),
        foodCourse = "Lunch",
        foodMeal = "Side",
        foodImage = R.drawable.chickencaesarsalad
    ),
    Food(
        foodId = 22,
        foodTitle = "Corn Chowder",
        foodDescription = "Sauté diced onions and minced garlic in butter until soft. Add corn kernels and diced potatoes, then pour in broth and bring to a simmer. Cook until the potatoes are tender. Add a splash of cream, season with salt and pepper, and garnish with chopped parsley. Serve this creamy corn chowder for a comforting meal.",
        foodTime = 15,
        foodServings = 2,
        foodYoutubeLink = "https://www.youtube.com/watch?v=XjBBqQqT5DA",
        foodIngredientImages = listOf(R.drawable.corn, R.drawable.potato, R.drawable.onion, R.drawable.garlic),
        foodCourse = "Lunch",
        foodMeal = "Soup",
        foodImage = R.drawable.cornchowder
    ),
    Food(
        foodId = 23,
        foodTitle = "Berry Salad",
        foodDescription = "Combine mixed berries with fresh spinach leaves in a bowl. Add crumbled cheese of your choice and toss gently. Drizzle honey over the salad for a touch of sweetness. Serve this vibrant and flavorful berry salad as a refreshing side dish.",
        foodTime = 10,
        foodServings = 1,
        foodYoutubeLink = "https://www.youtube.com/watch?v=K-JgAopLnZo",
        foodIngredientImages = listOf(R.drawable.berry, R.drawable.spinach, R.drawable.cheese),
        foodCourse = "Breakfast",
        foodMeal = "Appetizer",
        foodImage = R.drawable.berrysalad
    ),
    Food(
        foodId = 24,
        foodTitle = "Cheese Quesadilla",
        foodDescription = "Sprinkle cheese on a tortilla and fold it in half. Heat a skillet and cook the quesadilla on both sides until the cheese melts and the tortilla turns golden brown. Cut into wedges and serve this simple and delicious snack.",
        foodTime = 15,
        foodServings = 2,
        foodYoutubeLink = "https://www.youtube.com/watch?v=YbaTzT7PNTg",
        foodIngredientImages = listOf(R.drawable.cheese, R.drawable.bread, R.drawable.tomato),
        foodCourse = "Breakfast",
        foodMeal = "Side",
        foodImage = R.drawable.cheesequesadilla
    ),
    Food(
        foodId = 25,
        foodTitle = "Pasta Primavera",
        foodDescription = "Boil pasta until al dente, then set it aside. Sauté diced onions and minced garlic in olive oil until translucent. Add chopped tomatoes, peas, and carrots, cooking until the vegetables soften. Toss the cooked pasta with the vegetable mixture, season with salt and pepper, and drizzle with a bit of olive oil before serving.",
        foodTime = 25,
        foodServings = 2,
        foodYoutubeLink = "https://www.youtube.com/watch?v=eza6eFm5ioQ",
        foodIngredientImages = listOf(R.drawable.pasta, R.drawable.tomato, R.drawable.garlic, R.drawable.onion, R.drawable.oil, R.drawable.peas),
        foodCourse = "Lunch",
        foodMeal = "Main Dish",
        foodImage = R.drawable.pastaprimavera
    ),
    Food(
        foodId = 26,
        foodTitle = "Onion Rings",
        foodDescription = "Slice onions into rings and separate them. Dip the rings in a mixture of beaten egg and flour or breadcrumbs. Heat oil in a skillet and fry the onion rings until golden and crispy. Drain excess oil on paper towels and serve these crunchy onion rings as a delicious side dish or snack.",
        foodTime = 20,
        foodServings = 2,
        foodYoutubeLink = "https://www.youtube.com/watch?v=dcB5VU93AII",
        foodIngredientImages = listOf(R.drawable.onion, R.drawable.flour, R.drawable.egg),
        foodCourse = "Lunch",
        foodMeal = "Appetizer",
        foodImage = R.drawable.onionrings
    ),
    Food(
        foodId = 27,
        foodTitle = "Honey Mustard Chicken",
        foodDescription = "Mix honey and mustard to create a marinade. Coat chicken pieces in the marinade and let them sit for a while. Grill or bake the chicken until fully cooked and glazed. Garnish with a sprinkle of chopped parsley and serve this sweet and tangy chicken with your favorite sides.",
        foodTime = 35,
        foodServings = 3,
        foodYoutubeLink = "https://www.youtube.com/watch?v=duYwAwG3zIc",
        foodIngredientImages = listOf(R.drawable.chicken, R.drawable.honey, R.drawable.butter, R.drawable.mustard),
        foodCourse = "Lunch",
        foodMeal = "Main Dish",
        foodImage = R.drawable.honeymustardchicken
    ),
    Food(
        foodId = 28,
        foodTitle = "Spinach and Cheese Stuffed Chicken",
        foodDescription = "Flatten chicken breasts and stuff them with a mixture of spinach and cheese. Secure with toothpicks. Sear the stuffed chicken in a skillet until browned, then bake until the chicken is cooked through. Remove the toothpicks before serving this flavorful stuffed chicken.",
        foodTime = 45,
        foodServings = 4,
        foodYoutubeLink = "https://www.youtube.com/watch?v=zUeSdsJYQxs",
        foodIngredientImages = listOf(R.drawable.chicken, R.drawable.spinach, R.drawable.cheese, R.drawable.garlic, R.drawable.butter),
        foodCourse = "Dinner",
        foodMeal = "Main Dish",
        foodImage = R.drawable.spinachandcheesestuffedchicken
    ),
    Food(
        foodId = 29,
        foodTitle = "Lentil Curry",
        foodDescription = "Cook lentils until tender, then set them aside. Sauté diced onions and minced garlic until fragrant. Add diced tomatoes and spices like curry powder, cumin, and turmeric. Stir in the cooked lentils and let the flavors meld together. Garnish with chopped cilantro and serve this aromatic lentil curry with rice or naan.",
        foodTime = 15,
        foodServings = 3,
        foodYoutubeLink = "https://www.youtube.com/watch?v=3C-DQrS5L2Y",
        foodIngredientImages = listOf(R.drawable.lentil, R.drawable.onion, R.drawable.garlic),
        foodCourse = "Dinner",
        foodMeal = "Appetizer",
        foodImage = R.drawable.lentilcurry
    ),
    Food(
        foodId = 30,
        foodTitle = "Garlic Parmesan Roasted Potatoes",
        foodDescription = "Cut potatoes into wedges and toss them with minced garlic, grated Parmesan cheese, olive oil, salt, and pepper. Spread the seasoned potatoes on a baking sheet and roast until crispy and golden brown. Garnish with chopped parsley before serving these flavorful roasted potatoes.",
        foodTime = 25,
        foodServings = 4,
        foodYoutubeLink = "https://www.youtube.com/watch?v=L1lUQiIsCdE",
        foodIngredientImages = listOf(R.drawable.potato, R.drawable.garlic, R.drawable.cheese, R.drawable.oil),
        foodCourse = "Lunch",
        foodMeal = "Side",
        foodImage = R.drawable.garlicparmesanroastedpotatoes
    ),
    Food(
        foodId = 31,
        foodTitle = "Cheesy Garlic Breadsticks",
        foodDescription = "Mix grated cheese, minced garlic, and melted butter in a bowl. Spread the mixture on pre-made breadsticks or sliced baguette. Bake until the cheese is melted and bubbly. Serve these cheesy garlic breadsticks as a delightful appetizer or side dish.",
        foodTime = 15,
        foodServings = 2,
        foodYoutubeLink = "https://www.youtube.com/watch?v=qdAObPqiA0Y",
        foodIngredientImages = listOf(R.drawable.egg, R.drawable.butter, R.drawable.milk),
        foodCourse = "Dinner",
        foodMeal = "Appetizer",
        foodImage = R.drawable.cheesygarlicbreadsticks
    ),
    Food(
        foodId = 32,
        foodTitle = "Chicken Alfredo",
        foodDescription = "Cook pasta until al dente, then drain and set aside. Sauté diced chicken in butter until cooked through. Add cream and grated Parmesan cheese, stirring until the cheese melts and the sauce thickens. Toss the cooked pasta in the Alfredo sauce, garnish with parsley, and serve this creamy chicken Alfredo.",
        foodTime = 35,
        foodServings = 2,
        foodYoutubeLink = "https://www.youtube.com/watch?v=LPPcNPdq_j4",
        foodIngredientImages = listOf(R.drawable.chicken, R.drawable.butter, R.drawable.pasta, R.drawable.cheese),
        foodCourse = "Lunch",
        foodMeal = "Main Dish",
        foodImage = R.drawable.chickenalfredo
    ),
    Food(
        foodId = 33,
        foodTitle = "Berry Parfait",
        foodDescription = "Layer mixed berries, yogurt, and granola in a glass or bowl. Repeat the layers until the container is filled. Drizzle honey over the top for extra sweetness. Serve this colorful and nutritious berry parfait as a wholesome breakfast or a satisfying dessert.",
        foodTime = 15,
        foodServings = 1,
        foodYoutubeLink = "https://www.youtube.com/watch?v=aYwkYRm12QM",
        foodIngredientImages = listOf(R.drawable.berry, R.drawable.butter, R.drawable.milk),
        foodCourse = "Breakfast",
        foodMeal = "Appetizer",
        foodImage = R.drawable.berryparfait
    ),
    Food(
        foodId = 34,
        foodTitle = "Tomato Basil Pizza",
        foodDescription = "Roll out pizza dough into a circle. Spread a thin layer of tomato paste over the dough and sprinkle chopped tomatoes and basil leaves. Add grated cheese on top and bake until the crust is golden and the cheese melts. Slice and serve this homemade tomato basil pizza for a delicious meal.",
        foodTime = 55,
        foodServings = 6,
        foodYoutubeLink = "https://www.youtube.com/watch?v=--bv0V6ZjWI",
        foodIngredientImages = listOf(R.drawable.tomato, R.drawable.basil, R.drawable.cheese, R.drawable.flour),
        foodCourse = "Dinner",
        foodMeal = "Main Dish",
        foodImage = R.drawable.tomatobasilpizza
    ),
    Food(
        foodId = 35,
        foodTitle = "Potato Salad",
        foodDescription = "Boil potatoes until tender, then chop them into cubes. Mix the potatoes with boiled eggs, chopped onions, and a dressing made from mayonnaise, mustard, salt, and pepper. Chill the potato salad before serving this classic side dish at picnics or barbecues.",
        foodTime = 35,
        foodServings = 2,
        foodYoutubeLink = "https://www.youtube.com/watch?v=2Qzf0gyu6Qo",
        foodIngredientImages = listOf(R.drawable.potato, R.drawable.egg, R.drawable.onion),
        foodCourse = "Breakfast",
        foodMeal = "Side",
        foodImage = R.drawable.potatosalad
    )

)